name: build

on:
  pull_request:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - amazonlinux2
          - centos7
          - centos8
          - almalinux8
        platform:
          - linux/amd64
          - linux/arm64
        exclude:
          # AlmaLinux doesn't provide arm64 image now (2021-04-06)
          - distribution: almalinux8
            platform: linux/arm64

    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: build
        run: |
          make ${{ matrix.distribution }}
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::445285296882:role/rpm-repository-users-FluentBitRole-1C2C9XSCO4A2C
          role-session-tagging: true
      - name: upload
        run: |
          make upload
